services:
  database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: nexus123
      MYSQL_DATABASE: cash
    ports:
      - '3336:3306'

  mailcatcher:
    image: schickling/mailcatcher
    container_name: cms_mailcatcher
    ports:
      - 1080:1080
      - 1025:1025